replicaCount: 2
deploymentApiVersion: apps/v1
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
ingress:
  tls:
    enabled: true
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"

resources:
  limits:
   cpu: 100m
   memory: 128Mi
  requests:
   cpu: 100m
   memory: 128Mi

podDisruptionBudget:
  enabled: true
  # minAvailable: 1
  maxUnavailable: 1
livenessProbe:
  probeType: exec
  command:
    - /bin/grpc_health_probe
    - -addr
    - 127.0.0.1:5000
#    - -tls
#    - -tls-no-verify
readinessProbe:
  probeType: exec
  command:
    - /bin/grpc_health_probe
    - -addr
    - 127.0.0.1:5000
#    - -tls
#   - -tls-no-verify
