## Test docker image connect to DB

version: "3"

services:
  node:
    tty: true # Enables debugging capabilities when attached to this container.
    image: bitnami/node:10
    # command: sh -c 'npm install && npm start'
    ports:
      - 3000:3000
    volumes:
      - .:/app
  envoy-proxy:
    build:
      context: ./envoy-proxy
      dockerfile: Dockerfile
    ports:
      - 10000:10000
    environment:
      - ENDPOINT=node
    depends_on:
      - node
    restart: on-failure
#  grpc-gateway:
#    image: registry.gitlab.com/vdat/mcsvc/grpc-gateway/master:507f4f0c10e1395e65a43dc7e4a8723e04154437
#    ports:
#      - 8080:5000
#    environment:
#      - SMS_ENDPOINT=host.docker.internal:5000
#      - IDENTITY_ENDPOINT=localhost:5000
#    restart: on-failure
