## Test docker image connect to DB

version: "3"

services:
  node:
    tty: true # Enables debugging capabilities when attached to this container.
    image: bitnami/node:10
    # command: sh -c 'npm install && npm start'
    ports:
      - 3000:3000
    volumes:
      - .:/app